### ISSUE TITLE
t/002-get-set.t fails without Sereal::Decoder installed

### ISSUE THREAD

**Issue by andk** [burnersk/Dancer2-Session-Redis#9] opened 2016-08-13 04:25 UTC
As per subject. Grep:

http://search.cpan.org/grep?release=Dancer2-Session-Redis-0.006;string=Sereal::Decoder;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/72067770

Since it is a "recommends" not a "requires", tests would have to be optional to be consistent with the declaration.

HTH&&Thanks,

**Comment by SysPete** [comment] 2016-08-13 10:49
Fixed via commit f2090b75ef5a6e78e0fe8ffc2acb0d65a493c05b - many thanks for catching this one @andk. This was caused by me being too clever (and therefore way too stupid) when adding some new tests. :unamused: . Ho hum.

**Closed by SysPete** 2016-08-13 10:49 UTC
